[package]
name = "aoc23-day08"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.6"
hashbrown = "0.14.3"
micromap = "0.0.14"
rayon = "1.8.0"
regex = "1.10.2"
